### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by Gaurav-Verma07** [Gaurav-Verma07/backend#6]
Refactor `data_generation/views` file and make sure all the functions are properly working

**Comment by Quaxguy** [comment]
Elaborate on topic and i would like to work on it

**Comment by Gaurav-Verma07** [comment]
## Code  Structure:

1. Organize Files: Group related files into directories. Django follows the "app" structure, where each app contains models, views, templates, etc.
2. Split Large Files or Functions: Break down large files or functions into smaller, more manageable pieces.

## Modularization:

1. Reuse Code: Identify and extract reusable components. Create utility functions, mixins, or custom template tags.
2. DRY (Don't Repeat Yourself): Eliminate duplicated code. If a piece of logic is used in multiple places, consider creating a shared function or class.
3. Use Class-Based Views: If you're not already using them, consider converting function-based views to class-based views. They offer better organization and code reuse.

**Comment by Quaxguy** [comment]
ok ill work on it assign me

**Comment by Gaurav-Verma07** [comment]
hey buddy! any progress?
