### ISSUE TITLE
Need for contribution.md file 

### ISSUE THREAD

**Issue by deveshio** [Gaurav-Verma07/backend#7]
As your projects don't contain the contribution.md file 
it is getting difficult to get an understanding 
I know the 
steps are provided in readMe.md file 
but it is still better to have a contribution. md file instead of putting the steps in the readme. MD

**Comment by deveshio** [comment]
can you please provide specific details that I should keep in mind while writing your contribution.md
any specific details to remember 
like 
1. do's and don't does 
2. requirement for development 
3. how to make pr etc
4. any custom modifications etc.
5.

**Comment by Gaurav-Verma07** [comment]
except point 1, you can continue with rest 3 of them
